query SearchIssues($searchQuery: String!, $after: String) {
  search(type: ISSUE, query: $searchQuery, first: 20, after: $after) {
    edges {
      node {
        ... on Issue {
          assignees {
            totalCount
          }
          author {
            avatarUrl
            login
            url
          }
          createdAt
          id
          labels(orderBy: { field: NAME, direction: ASC }, first: 100) {
            edges {
              cursor
              node {
                color
                id
                name
              }
            }
          }
          title
          updatedAt
          url
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
